appProyectoDSWI_Tienda/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using appProyectoDSWI_Tienda.Models;
using appProyectoDSWI_Tienda.Permisos;

namespace appProyectoDSWI_Tienda.Controllers
{
    [Authorize]
    [PermisosRol(Models.Rol.Administrador)]
    public class CategoriaController : Controller
    {
        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);

        // GET: Categoria
        public ActionResult Index()
        {
            return View();
        }

        List<Categoria> listarCategoria()
        {
            List<Categoria> aCategorias = new List<Categoria>();
            SqlCommand cmd = new SqlCommand("SP_CATEGORIA", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Categoria objC = new Categoria()
                {
                    idCateg = int.Parse(dr[0].ToString()),
                    nomCateg = dr[1].ToString(),
                    desCateg = dr[2].ToString()
                };
                aCategorias.Add(objC);
            }
            cn.Close();
            return aCategorias;
        }

        public ActionResult listadoCategorias()
        {
            return View(listarCategoria());
        }

        public ActionResult nuevoCategoria()
        {
            return View(new Categoria());
        }

        [HttpPost]
        public ActionResult nuevoCategoria(Categoria objC)
        {
            if (!ModelState.IsValid)
            {
                return View(objC);
            }
            cn.Open();
            try
            {
                SqlCommand cmd = new SqlCommand("SP_REGISTROCATEGORIA", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@NOM", objC.nomCateg);
                cmd.Parameters.AddWithValue("@DES", objC.desCateg);
                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = ex.Message;
            }
            cn.Close();
            return RedirectToAction("listadoCategorias");
        }
    }
}

appProyectoDSWI_Tienda/Controllers/FabricanteController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using appProyectoDSWI_Tienda.Models;
using appProyectoDSWI_Tienda.Permisos;

namespace appProyectoDSWI_Tienda.Controllers
{
    [Authorize]
    [PermisosRol(Models.Rol.Administrador)]
    public class FabricanteController : Controller
    {
        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);

        // GET: Fabricante
        public ActionResult Index()
        {
            return View();
        }

        List<Fabricante> listarFabricantes()
        {
            List<Fabricante> aFabricantes = new List<Fabricante>();
            SqlCommand cmd = new SqlCommand("SP_FABRICANTE", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Fabricante objF = new Fabricante()
                {
                    idFabr = int.Parse(dr[0].ToString()),
                    nomFabr = dr[1].ToString(),
                    paisFabr = dr[2].ToString()
                };
                aFabricantes.Add(objF);
            }
            dr.Close();
            cn.Close();
            return aFabricantes;
        }

        List<Pais> listPais()
        {
            List<Pais> aPaises = new List<Pais>();
            SqlCommand cmd = new SqlCommand("SP_PAIS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Pais objPa = new Pais()
                {
                    idPais = int.Parse(dr[0].ToString()),
                    nomPais = dr[1].ToString()
                };
                aPaises.Add(objPa);
            }
            cn.Close();
            return aPaises;
        }

        public ActionResult ListadoPais()
        {
            return View(listPais());
        }

        public ActionResult listadoFabricantes()
        {
            return View(listarFabricantes());
        }

        public ActionResult nuevoFabricante()
        {
            ViewBag.pais = new SelectList(listPais(), "idPais", "nomPais");
            return View(new FabricanteA());
        }

        [HttpPost]
        public ActionResult nuevoFabricante(FabricanteA objF)
        {
            if (!ModelState.IsValid)
            {
                return View(objF);
            }
            cn.Open();
            try
            {
                SqlCommand cmd = new SqlCommand("SP_REGISTROFABRICANTE", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@NOM", objF.nomFabr);
                cmd.Parameters.AddWithValue("@PAI", objF.pais);
                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = ex.Message;
            }
            cn.Close();
            return RedirectToAction("listadoFabricantes");
        }

    }
}

appProyectoDSWI_Tienda/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using appProyectoDSWI_Tienda.Models;
using appProyectoDSWI_Tienda.Permisos;

namespace appProyectoDSWI_Tienda.Controllers
{
    [Authorize]
    [PermisosRol(Models.Rol.Administrador)]
    public class ProductoController : Controller
    {
        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);

        // GET: Producto
        public ActionResult Index()
        {
            return View();
        }

        List<Producto> listarProductos()
        {
            List<Producto> aProductos = new List<Producto>();
            SqlCommand cmd = new SqlCommand("SP_LISTAPRODUCTO", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Producto objP = new Producto()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString(),
                    descripcion = dr[2].ToString(),
                    fabricante = dr[3].ToString(),
                    categoria = dr[4].ToString(),
                    precio = double.Parse(dr[5].ToString()),
                    foto = dr[6].ToString()
                };
                aProductos.Add(objP);
            }
            dr.Close();
            cn.Close();
            return aProductos;
        }

        List<Fabricante> listFabricanteAs()
        {
            List<Fabricante> aFabricantes = new List<Fabricante>();
            SqlCommand cmd = new SqlCommand("SP_FABRICANTE", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Fabricante objF = new Fabricante()
                {
                    idFabr = int.Parse(dr[0].ToString()),
                    nomFabr = dr[1].ToString(),
                    paisFabr = dr[2].ToString()
                };
                aFabricantes.Add(objF);
            }
            cn.Close();
            return aFabricantes;
        }
        List<Categoria> listCategoria()
        {
            List<Categoria> aCategorias = new List<Categoria>();
            SqlCommand cmd = new SqlCommand("SP_CATEGORIA", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                Categoria objC = new Categoria()
                {
                    idCateg = int.Parse(dr[0].ToString()),
                    nomCateg = dr[1].ToString(),
                    desCateg = dr[2].ToString()
                };
                aCategorias.Add(objC);
            }
            cn.Close();
            return aCategorias;
        }

        public ActionResult listadoProductos()
        {
            return View(listarProductos());
        }

        void CRUD(String proceso, List<SqlParameter> pars)
        {
            cn.Open();
            try
            {
                SqlCommand cmd = new SqlCommand(proceso, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddRange(pars.ToArray());
                cmd.ExecuteNonQuery();
            }
            catch (Exception)
            {
            }
            cn.Close();
        }

        public ActionResult nuevoProducto()
        {
            ViewBag.fabricante = new SelectList(listFabricanteAs(), "idFabr", "nomFabr");
            ViewBag.categoria = new SelectList(listCategoria(), "idCateg", "nomCateg");
            return View(new ProductoA());
        }

        [HttpPost]
        public ActionResult nuevoProducto(ProductoA objP, HttpPostedFileBase f)
        {
            if (f == null)
            {
                ViewBag.mensaje = "Seleccione una imagen";
                return View(objP);
            }
            if (Path.GetExtension(f.FileName) != ".jpg")
            {
                ViewBag.mensaje = "Debe ser .JPG";
                return View(objP);
            }
            List<SqlParameter> lista = new List<SqlParameter>()
            {
                new SqlParameter(){ParameterName="@NOM",SqlDbType=SqlDbType.VarChar,Value=objP.nombre},
                new SqlParameter(){ParameterName="@DES",SqlDbType=SqlDbType.VarChar,Value=objP.descripcion},
                new SqlParameter(){ParameterName="@FAB",SqlDbType=SqlDbType.Int,Value=objP.fabricante},
                new SqlParameter(){ParameterName="@CAT",SqlDbType=SqlDbType.Int,Value=objP.categoria },
                new SqlParameter(){ParameterName="@PRE",SqlDbType=SqlDbType.Decimal,Value=objP.precio },
                new SqlParameter(){ParameterName="@FOT",SqlDbType=SqlDbType.VarChar,Value="~/fotos_productos/"+Path.GetFileName(f.FileName) }
            };
            ViewBag.fabricante = new SelectList(listFabricanteAs(), "codigo", "nombre");
            ViewBag.categoria = new SelectList(listCategoria(), "codigo", "nombre");
            CRUD("SP_REGISTROPRODUCTO", lista);
            f.SaveAs(Path.Combine(Server.MapPath("~/fotos_productos/"),
            Path.GetFileName(f.FileName)));
            return RedirectToAction("listadoProductos");
        }





    }
}

appProyectoDSWI_Tienda/Views/Tienda/Comprar.cshtml
@model IEnumerable<appProyectoDSWI_Tienda.Models.DetalleVenta>

@{
    ViewBag.Title = "Comprar";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<section class="panel panel-primary">
    <section class="panel panel-heading">
        PROCESO DE COMPRA DE PRODUCTOS
    </section> @Html.Partial("_partialComprar")
    <section id="monto">
        TOTAL A PAGAR S/ @(((decimal)ViewBag.monto).ToString("0.00"))
    </section>
    <section>
        @Html.ActionLink("< Retornar", "carritoCompras", null, new { @class = "btn btn-success" }) @Html.ActionLink("Pagar", "Pago", null, new { @class = "btn btn-danger" })
    </section>
    <br />
    <br />
</section>

appProyectoDSWI_Tienda/Views/Tienda/Final.cshtml
@{
    ViewBag.Title = "Final";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<style>
    .tamaño {
        width: 350px;
        height: 350px;
        display: block;
        margin: auto;
    }
</style>
<section>
    <h2>   FELICITACIONES   </h2>
    <img class="tamaño" src="~/Imagenes/pago.jpg" /> <h4>MONTO CANCELADO: s/ @ViewBag.mt</h4>
    <h2>   MUCHAS GRACIAS POR SU COMPRA   </h2>
    <br />
    <br />
    <section id="botoncentral" style="display: flex; align-items: center; justify-content: center;" >
        @Html.ActionLink("ACEPTAR", "limpiarCarrito", null, new { @class = "btn btn-success" })
    </section>
    <br />
    <br />
</section>

appProyectoDSWI_Tienda/Views/Tienda/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h4>Bienvenido - Seleccione un modulo para iniciar</h4>
<section id="columna">
    <table>
        <tr>
            <td><img id="logo" src="~/Imagenes/cliente.png" /></td>
            <td>
                CLIENTES<br /> <br />Agregar - Listar
            </td>
        </tr>
    </table>
</section>
<section id="columna">
    <table>
        <tr>
            <td><img id="logo" src="~/Imagenes/categoria.png" /></td>
            <td>
                CATEGORIA<br /> <br />@Html.ActionLink("Agregar", "nuevoCategoria", "Categoria") - @Html.ActionLink("Listar", "nuevoCategoria", "Categoria")
            </td>
        </tr>
    </table>
</section>
<section id="columna">
    <table>
        <tr>
            <td><img id="logo" src="~/Imagenes/fabricante.jpeg" /></td>
            <td>
                FABRICANTE<br /> <br />@Html.ActionLink("Agregar", "nuevoFabricante", "Fabricante") - @Html.ActionLink("Listar", "listadoFabricantes", "Fabricante")
            </td>
        </tr>
    </table>
</section>
<section id="columna">
    <table>
        <tr>
            <td><img id="logo" src="~/Imagenes/productos.png" /></td>
            <td>
                PRODUCTO<br /> <br />@Html.ActionLink("Agregar", "nuevoProducto", "Producto") - @Html.ActionLink("Listar", "listadoProductos", "Producto")
            </td>
        </tr>
    </table>
</section>
<section id="columna">
    <table>
        <tr>
            <td><img id="logo" src="~/Imagenes/ventas.jpg" /></td>
            <td>
                VENTA<br /> <br />
                @Html.ActionLink("Agregar", "carritoCompras", "Tienda") - Listar - Buscar
            </td>
        </tr>
    </table>
</section>

appProyectoDSWI_Tienda/Views/Tienda/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutPrincipal2.cshtml";
}

<h2>INGRESO</h2>
<div class="row" style="display: flex; align-items: center; justify-content: center;">
    <form action="@Url.Action("Login","Tienda")" class="bg-info" style="padding: 15px; width: 300px; height: 220px; align-items: center; " method="post">
        <div class="form-group" style="font-size: 15px">
            <label>USUARIO : </label>
            <input class="form-control" type="email" name="correo" />
        </div>
        <div class="form-group" style="font-size: 15px">
            <label>CONTRASEÑA : </label>
            <input class="form-control" type="password" name="clave" />
        </div>
        <div class="form-group" style="display: flex; align-items: center; justify-content: center;">
            <button type="submit" class="btn btn-success">INGRESAR</button>
        </div>
    </form>
</div>

appProyectoDSWI_Tienda/Views/Tienda/Pago.cshtml
@model IEnumerable<appProyectoDSWI_Tienda.Models.DetalleVenta>

@{
    ViewBag.Title = "Pago";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h5>
    @Html.ActionLink("Retornar", "carritoCompras", "", new { @class = "btn btn-success" })
</h5>
<section class="panel panel-primary">
    <section class="panel-heading">
        CONFIRMAR COMPRA
    </section>
    <section class="panel-body">
        @using (Html.BeginForm("Final", "Tienda"))
        {
            @Html.ActionLink("ACEPTAR", "Final", "", new { @class = "btn btn-success" })
        } @Html.Partial("_partialComprar") <div id="monto">MONTO TOTAL S/ @(((decimal)ViewBag.mt).ToString("0.00"))</div>
    </section>
    <br />
    <br />
</section>

appProyectoDSWI_Tienda/Views/Tienda/SinAutorizacion.cshtml
@{
    ViewBag.Title = "SinAutorizacion";
    Layout = "~/Views/Shared/_LayoutPrincipal2.cshtml";
}

<h2>@ViewBag.Message</h2>
<br />
<br />
<section id="botoncentral" style="display: flex; align-items: center; justify-content: center;">
    @Html.ActionLink("ACEPTAR", "Index", "Tienda", new { @class = "btn btn-success" })
</section>

appProyectoDSWI_Tienda/Views/Tienda/carritoCompras.cshtml
@model IEnumerable<appProyectoDSWI_Tienda.Models.Producto>

@{
    ViewBag.Title = "carritoCompras";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2>CARRITO DE COMPRAS</h2>
<p>
    @Html.ActionLink("Realizar Compra", "Comprar", null, new { @class = "btn btn-success" })
</p> @Html.Partial("_partialProducto");

appProyectoDSWI_Tienda/Views/Tienda/seleccionaProducto.cshtml
@model appProyectoDSWI_Tienda.Models.Producto

@{
    ViewBag.Title = "seleccionaProducto";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<section id="columna1">
    @Html.Partial("_PartialRegistro")
</section>
<section id="columna2">
    @using (Html.BeginForm("agregarProducto", "Tienda"))
    {
        <section class="panel panel-primary">
            <section class="panel-heading">
                PROCESO DE SELECCIÓN
            </section>
            <section class="panel-body">
                @Html.Hidden("id", Model.codigo, new
                {
                    placeholder = "(Texto de búsqueda)", @class = "form-control"
                })
                <h5>INGRESE CANTIDAD</h5> @Html.TextBox("cant", "", new
                {
                    placeholder = "(Ingrese cantidad)", @class = "form-control"
                })
                @Html.ActionLink("CANCELAR", "carritoCompras", "",
                new { @class = "btn btn-primary" })
                <input type="submit" value="ACEPTAR" class="btn btn-danger" />
            </section>
        </section>
    }
</section>